[package]
name = "klotski"
version = "0.1.0"
description  = "A simple Klotski puzzle solver."
license = "MIT"
edition = "2024"

[profile.release]
debug = true

[dependencies]
log = "0.4.27"
env_logger = "0.11.8"
clap = { version = "4.5.39", features = ["derive"] }
